# Generated by Django 5.1.4 on 2025-07-16 00:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_costgroup_costsubgroup_historicalcostgroup_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="costsubgroup",
            name="value_stimated",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Estimated value of the cost subgroup",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Estimated Value",
            ),
        ),
        migrations.AddField(
            model_name="historicalcostsubgroup",
            name="value_stimated",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Estimated value of the cost subgroup",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Estimated Value",
            ),
        ),
    ]
