# Generated by Django 5.1.4 on 2025-07-16 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_costsubgroup_value_stimated_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalmodelproject",
            name="area_padrao",
        ),
        migrations.RemoveField(
            model_name="historicalmodelproject",
            name="materiais_padrao",
        ),
        migrations.RemoveField(
            model_name="modelproject",
            name="area_padrao",
        ),
        migrations.RemoveField(
            model_name="modelproject",
            name="materiais_padrao",
        ),
    ]
