# Generated by Django 5.1.4 on 2025-07-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_remove_historicalmodelproject_area_padrao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="phaseproject",
            name="prerequisite_phases",
            field=models.ManyToManyField(
                blank=True,
                help_text="Phases within this project that must be completed before this one",
                related_name="dependent_phases",
                to="projects.phaseproject",
                verbose_name="Prerequisite Phases",
            ),
        ),
    ]
