# Generated by Django 5.1.4 on 2025-07-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_phaseproject_prerequisite_phases"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="payment_date",
            field=models.DateField(
                blank=True,
                help_text="Payment date of the contract",
                null=True,
                verbose_name="Payment Date",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="sign_date",
            field=models.DateField(
                blank=True,
                help_text="Signature date of the contract (when it was signed)",
                null=True,
                verbose_name="Signature Date",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="payment_date",
            field=models.DateField(
                blank=True,
                help_text="Payment date of the contract",
                null=True,
                verbose_name="Payment Date",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="sign_date",
            field=models.DateField(
                blank=True,
                help_text="Signature date of the contract (when it was signed)",
                null=True,
                verbose_name="Signature Date",
            ),
        ),
    ]
