# Generated by Django 5.1.4 on 2025-07-18 03:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_alter_elevationchoice_locale_code_and_more"),
        (
            "projects",
            "0006_alter_contract_payment_date_alter_contract_sign_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="contract_value",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Total value of all units in the contract - this value comes from the lead - automatically updated when the contract is created",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Contract Value",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="lead",
            field=models.ForeignKey(
                help_text="Lead que originou este contrato",
                limit_choices_to={"status": 2},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contract",
                to="leads.lead",
                verbose_name="Lead Origem",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="contract_value",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Total value of all units in the contract - this value comes from the lead - automatically updated when the contract is created",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Contract Value",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Lead que originou este contrato",
                limit_choices_to={"status": 2},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="leads.lead",
                verbose_name="Lead Origem",
            ),
        ),
    ]
