# Generated by Django 5.1.4 on 2025-07-24 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_alter_elevationchoice_locale_code_and_more"),
        ("projects", "0007_alter_contract_contract_value_alter_contract_lead_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="lead",
            field=models.ForeignKey(
                help_text="Lead que originou este contrato",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contract",
                to="leads.lead",
                verbose_name="Lead Origem",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Lead que originou este contrato",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="leads.lead",
                verbose_name="Lead Origem",
            ),
        ),
    ]
