# Generated by Django 5.1.4 on 2025-08-03 14:15

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_projects360_historicalprojects360"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contractproject",
            name="data_atualizacao",
        ),
        migrations.RemoveField(
            model_name="contractproject",
            name="data_reserva",
        ),
        migrations.RemoveField(
            model_name="contractproject",
            name="data_venda_confirmada",
        ),
        migrations.RemoveField(
            model_name="contractproject",
            name="desconto_aplicado",
        ),
        migrations.AddField(
            model_name="contractproject",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="created at",
                verbose_name="Created At",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contractproject",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
        ),
        migrations.AlterField(
            model_name="contractproject",
            name="preco_venda_unidade",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Preço da unidade vendida no mercado",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Preço de Venda da Unidade",
            ),
        ),
    ]
