# Generated by Django 5.1.4 on 2025-07-24 12:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BrokermintWebhook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único do webhook recebido",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID do Webhook",
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp de quando o webhook foi recebido",
                        verbose_name="Recebido em",
                    ),
                ),
                (
                    "http_method",
                    models.CharField(
                        default="POST",
                        help_text="Método HTTP usado na requisição (geralmente POST)",
                        max_length=10,
                        verbose_name="Método HTTP",
                    ),
                ),
                (
                    "headers",
                    models.JSONField(
                        help_text="Todos os headers da requisição para análise de autenticação",
                        verbose_name="Headers HTTP",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        help_text="Dados JSON enviados pelo Brokermint",
                        verbose_name="Payload JSON",
                    ),
                ),
                (
                    "raw_body",
                    models.TextField(
                        help_text="Corpo completo da requisição para debug e reprocessamento",
                        verbose_name="Corpo Bruto",
                    ),
                ),
                (
                    "processed",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se o webhook foi processado com sucesso",
                        verbose_name="Processado",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Quando o webhook foi processado com sucesso",
                        null=True,
                        verbose_name="Processado em",
                    ),
                ),
                (
                    "processing_error",
                    models.TextField(
                        blank=True,
                        help_text="Detalhes do erro caso o processamento falhe",
                        verbose_name="Erro de Processamento",
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Número de tentativas de reprocessamento após falhas",
                        verbose_name="Tentativas de Reprocessamento",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        blank=True,
                        help_text="Tipo de evento identificado no payload (ex: transaction.updated)",
                        max_length=100,
                        verbose_name="Tipo de Evento",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="ID da transação do Brokermint relacionada ao evento",
                        max_length=50,
                        verbose_name="ID da Transação",
                    ),
                ),
                (
                    "brokermint_event_id",
                    models.CharField(
                        blank=True,
                        help_text="ID único do evento fornecido pelo Brokermint (para deduplicação)",
                        max_length=100,
                        verbose_name="ID do Evento Brokermint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Brokermint",
                "verbose_name_plural": "Webhooks Brokermint",
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(fields=["processed"], name="webhook_processed_idx"),
                    models.Index(fields=["event_type"], name="webhook_event_type_idx"),
                    models.Index(
                        fields=["transaction_id"], name="webhook_transaction_idx"
                    ),
                    models.Index(fields=["received_at"], name="webhook_received_idx"),
                    models.Index(
                        fields=["brokermint_event_id"], name="webhook_event_id_idx"
                    ),
                ],
            },
        ),
    ]
