# Generated by Django 5.0.1 on 2025-08-11 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = []
