# Generated by Django 5.0.1 on 2025-08-11 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0002_auto_20250811_2238"),
    ]

    operations = []
