# Generated by Django 5.0.1 on 2025-08-11 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0003_auto_20250811_2243"),
        ("integrations", "000X_remove_webhook"),
    ]

    operations = []
