# Generated by Django 5.0.1 on 2025-08-11 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0004_merge_0003_auto_20250811_2243_000X_remove_webhook"),
    ]

    operations = []
