# Generated by Django 5.0.1 on 2025-08-12 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0006_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brokerminttransaction",
            name="bedrooms",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Quartos"
            ),
        ),
        migrations.AlterField(
            model_name="brokerminttransaction",
            name="external_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ID Externo"
            ),
        ),
        migrations.AlterField(
            model_name="brokerminttransaction",
            name="full_baths",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Banheiros"
            ),
        ),
        migrations.AlterField(
            model_name="brokerminttransaction",
            name="half_baths",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Lavabos"
            ),
        ),
        migrations.AlterField(
            model_name="brokerminttransaction",
            name="home_model",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Modelo Casa"
            ),
        ),
        migrations.AlterField(
            model_name="brokerminttransaction",
            name="legal_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Descrição Legal"
            ),
        ),
        migrations.AlterField(
            model_name="brokerminttransaction",
            name="parcel_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Parcel ID"
            ),
        ),
        migrations.AlterField(
            model_name="brokerminttransaction",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Preço",
            ),
        ),
        migrations.AlterField(
            model_name="brokerminttransaction",
            name="representing",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Representando"
            ),
        ),
        migrations.AlterField(
            model_name="brokerminttransaction",
            name="sales_volume",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="brokerminttransaction",
            name="total_gross_commission",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
    ]
