# Generated by Django 5.0.1 on 2025-08-12 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0007_alter_brokerminttransaction_bedrooms_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brokerminttransaction",
            name="has_signature_activity",
            field=models.BooleanField(
                default=False, verbose_name="Tem atividade de assinatura"
            ),
        ),
        migrations.AddField(
            model_name="brokerminttransaction",
            name="is_contract_signed",
            field=models.BooleanField(default=False, verbose_name="Contrato assinado"),
        ),
        migrations.AddField(
            model_name="brokerminttransaction",
            name="last_activity_check",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Última verificação de atividades"
            ),
        ),
        migrations.AlterField(
            model_name="brokerminttransaction",
            name="address",
            field=models.CharField(max_length=200, null=True, verbose_name="Endereço"),
        ),
        migrations.AlterField(
            model_name="brokerminttransaction",
            name="block",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Quadra"
            ),
        ),
        migrations.AlterField(
            model_name="brokerminttransaction",
            name="builder_fee",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Taxa Builder"
            ),
        ),
        migrations.AlterField(
            model_name="brokerminttransaction",
            name="building_sqft",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="SQFT Construção"
            ),
        ),
        migrations.AlterField(
            model_name="brokerminttransaction",
            name="city",
            field=models.CharField(max_length=100, null=True, verbose_name="Cidade"),
        ),
        migrations.AlterField(
            model_name="brokerminttransaction",
            name="county",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="County"
            ),
        ),
        migrations.AlterField(
            model_name="brokerminttransaction",
            name="custom_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ID Customizado"
            ),
        ),
        migrations.AlterField(
            model_name="brokerminttransaction",
            name="draw_1",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Draw 1"
            ),
        ),
        migrations.AlterField(
            model_name="brokerminttransaction",
            name="draw_2",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Draw 2"
            ),
        ),
        migrations.AlterField(
            model_name="brokerminttransaction",
            name="draw_3",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Draw 3"
            ),
        ),
        migrations.AlterField(
            model_name="brokerminttransaction",
            name="draw_4",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Draw 4"
            ),
        ),
        migrations.AlterField(
            model_name="brokerminttransaction",
            name="draw_5",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Draw 5"
            ),
        ),
        migrations.AlterField(
            model_name="brokerminttransaction",
            name="estimated_construction_cost",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="brokerminttransaction",
            name="hard_costs",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Hard Costs"
            ),
        ),
        migrations.AlterField(
            model_name="brokerminttransaction",
            name="has_detailed_data",
            field=models.BooleanField(
                default=False, null=True, verbose_name="Dados Detalhados Carregados"
            ),
        ),
        migrations.AlterField(
            model_name="brokerminttransaction",
            name="lot",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Lote"
            ),
        ),
        migrations.AlterField(
            model_name="brokerminttransaction",
            name="rge",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="RGE"
            ),
        ),
        migrations.AlterField(
            model_name="brokerminttransaction",
            name="sec",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="SEC"
            ),
        ),
        migrations.AlterField(
            model_name="brokerminttransaction",
            name="soft_costs",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Soft Costs"
            ),
        ),
        migrations.AlterField(
            model_name="brokerminttransaction",
            name="state",
            field=models.CharField(max_length=10, null=True, verbose_name="Estado"),
        ),
        migrations.AlterField(
            model_name="brokerminttransaction",
            name="subdivision",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Subdivisão"
            ),
        ),
        migrations.AlterField(
            model_name="brokerminttransaction",
            name="transaction_type",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Tipo Transação"
            ),
        ),
        migrations.AlterField(
            model_name="brokerminttransaction",
            name="twp",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="TWP"
            ),
        ),
        migrations.AlterField(
            model_name="brokerminttransaction",
            name="unit",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Unidade"
            ),
        ),
        migrations.AlterField(
            model_name="brokerminttransaction",
            name="zip",
            field=models.CharField(max_length=20, null=True, verbose_name="CEP"),
        ),
        migrations.AddIndex(
            model_name="brokerminttransaction",
            index=models.Index(
                fields=["last_activity_check"], name="integration_last_ac_87c64b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="brokerminttransaction",
            index=models.Index(
                fields=["is_contract_signed"], name="integration_is_cont_244e08_idx"
            ),
        ),
    ]
