# Generated by Django 5.0.1 on 2025-08-12 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0008_brokerminttransaction_has_signature_activity_and_more"),
    ]

    operations = []
