# Generated by Django 5.0.1 on 2025-08-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0009_auto_20250812_1342"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brokermintdocument",
            name="name",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="brokermintdocument",
            name="url",
            field=models.URLField(max_length=1000),
        ),
    ]
