# Generated by Django 5.1.4 on 2025-07-13 21:55

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="County",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Official county name",
                        max_length=100,
                        unique=True,
                        verbose_name="County Name",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short code for county",
                        max_length=10,
                        unique=True,
                        verbose_name="County Code",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        default="FL",
                        help_text="State abbreviation",
                        max_length=2,
                        verbose_name="State",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether county is available for selection",
                        verbose_name="Is Active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "County",
                "verbose_name_plural": "Counties",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalHOA",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the Homeowners Association",
                        max_length=200,
                        verbose_name="HOA Name",
                    ),
                ),
                (
                    "has_special_permit_rules",
                    models.BooleanField(
                        default=False,
                        help_text="Does this HOA have special permit requirements?",
                        verbose_name="Special Permit Rules",
                    ),
                ),
                (
                    "permit_requirements",
                    models.TextField(
                        blank=True,
                        help_text="Details of any special permit requirements for this HOA",
                        verbose_name="Permit Requirements",
                    ),
                ),
                (
                    "contact_info",
                    models.TextField(
                        blank=True,
                        help_text="Contact information for the HOA management or board",
                        verbose_name="Contact Information",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is this HOA currently active?",
                        verbose_name="Active HOA",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Date and time when the HOA was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Date and time when the HOA was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "county",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="County where the HOA is located",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.county",
                        verbose_name="County",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Homeowners Association",
                "verbose_name_plural": "historical Homeowners Associations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalRealtor",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Realtor full name",
                        max_length=100,
                        verbose_name="Realtor Name",
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        help_text="Primary phone number",
                        max_length=128,
                        region=None,
                        verbose_name="Realtor Phone",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Primary email address",
                        max_length=254,
                        verbose_name="Realtor Email",
                    ),
                ),
                (
                    "default_commission_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Usually Realtor commission rate",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Realtor Commission Rate",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether county is available for selection",
                        verbose_name="Is Active",
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Realtor",
                "verbose_name_plural": "historical Realtors",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HOA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the Homeowners Association",
                        max_length=200,
                        verbose_name="HOA Name",
                    ),
                ),
                (
                    "has_special_permit_rules",
                    models.BooleanField(
                        default=False,
                        help_text="Does this HOA have special permit requirements?",
                        verbose_name="Special Permit Rules",
                    ),
                ),
                (
                    "permit_requirements",
                    models.TextField(
                        blank=True,
                        help_text="Details of any special permit requirements for this HOA",
                        verbose_name="Permit Requirements",
                    ),
                ),
                (
                    "contact_info",
                    models.TextField(
                        blank=True,
                        help_text="Contact information for the HOA management or board",
                        verbose_name="Contact Information",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is this HOA currently active?",
                        verbose_name="Active HOA",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the HOA was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the HOA was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "county",
                    models.ForeignKey(
                        help_text="County where the HOA is located",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hoas",
                        to="core.county",
                        verbose_name="County",
                    ),
                ),
            ],
            options={
                "verbose_name": "Homeowners Association",
                "verbose_name_plural": "Homeowners Associations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Realtor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Realtor full name",
                        max_length=100,
                        unique=True,
                        verbose_name="Realtor Name",
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        help_text="Primary phone number",
                        max_length=128,
                        region=None,
                        verbose_name="Realtor Phone",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Primary email address",
                        max_length=254,
                        verbose_name="Realtor Email",
                    ),
                ),
                (
                    "default_commission_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Usually Realtor commission rate",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Realtor Commission Rate",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether county is available for selection",
                        verbose_name="Is Active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "usually_works_in",
                    models.ManyToManyField(
                        help_text="Counties where realtor works",
                        to="core.county",
                        verbose_name="Counties",
                    ),
                ),
            ],
            options={
                "verbose_name": "Realtor",
                "verbose_name_plural": "Realtors",
                "ordering": ["name"],
            },
        ),
    ]
