# Generated by Django 5.1.4 on 2025-07-13 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("leads", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallead",
            name="house_model",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Selected house model type",
                limit_choices_to={"is_active": True},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="projects.modelproject",
                verbose_name="House Model",
            ),
        ),
        migrations.AddField(
            model_name="historicallead",
            name="realtor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Realtor involved in this deal (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.realtor",
                verbose_name="Realtor",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="county",
            field=models.ForeignKey(
                help_text="County where property is located",
                on_delete=django.db.models.deletion.RESTRICT,
                to="core.county",
                verbose_name="County",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created this lead",
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="elevation",
            field=models.ForeignKey(
                help_text="Elevation specification for the house",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="leads",
                to="leads.elevationchoice",
                verbose_name="House Elevation",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="hoa",
            field=models.ForeignKey(
                blank=True,
                help_text="Homeowners Association (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="leads",
                to="core.hoa",
                verbose_name="HOA",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="house_model",
            field=models.ForeignKey(
                help_text="Selected house model type",
                limit_choices_to={"is_active": True},
                on_delete=django.db.models.deletion.RESTRICT,
                to="projects.modelproject",
                verbose_name="House Model",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="realtor",
            field=models.ForeignKey(
                blank=True,
                help_text="Realtor involved in this deal (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="core.realtor",
                verbose_name="Realtor",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="status",
            field=models.ForeignKey(
                help_text="Current status in the lead pipeline",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="leads",
                to="leads.statuschoice",
                verbose_name="Lead Status",
            ),
        ),
        migrations.AddField(
            model_name="historicallead",
            name="status",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Current status in the lead pipeline",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="leads.statuschoice",
                verbose_name="Lead Status",
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["status", "created_at"], name="leads_lead_status__81928f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["county", "status"], name="leads_lead_county__d42270_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["client_email"], name="leads_lead_client__68d0d2_idx"
            ),
        ),
    ]
