# Generated by Django 5.1.4 on 2025-07-17 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elevationchoice",
            name="locale_code",
            field=models.CharField(
                help_text="Elevtions Codes (Contemporary, Farm, N/A)",
                max_length=10,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicallead",
            name="status",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=1,
                help_text="Current status in the lead pipeline",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="leads.statuschoice",
                verbose_name="Lead Status",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.ForeignKey(
                default=1,
                help_text="Current status in the lead pipeline",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="leads",
                to="leads.statuschoice",
                verbose_name="Lead Status",
            ),
        ),
    ]
