# Generated by Django 5.0.1 on 2025-08-13 22:36

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_alter_elevationchoice_locale_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallead",
            name="realtor_email",
            field=models.EmailField(
                blank=True,
                help_text="Email address of the realtor (if applicable)",
                max_length=254,
                verbose_name="Realtor Email",
            ),
        ),
        migrations.AddField(
            model_name="historicallead",
            name="realtor_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the realtor (if applicable)",
                max_length=200,
                verbose_name="Realtor Name",
            ),
        ),
        migrations.AddField(
            model_name="historicallead",
            name="realtor_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Phone number of the realtor (if applicable)",
                max_length=128,
                region=None,
                verbose_name="Realtor Phone",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="realtor_email",
            field=models.EmailField(
                blank=True,
                help_text="Email address of the realtor (if applicable)",
                max_length=254,
                verbose_name="Realtor Email",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="realtor_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the realtor (if applicable)",
                max_length=200,
                verbose_name="Realtor Name",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="realtor_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Phone number of the realtor (if applicable)",
                max_length=128,
                region=None,
                verbose_name="Realtor Phone",
            ),
        ),
    ]
