# Generated by Django 5.0.1 on 2025-08-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0004_historicallead_realtor_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallead",
            name="hoa_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the Homeowners Association (if applicable)",
                max_length=200,
                verbose_name="HOA Name",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="hoa_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the Homeowners Association (if applicable)",
                max_length=200,
                verbose_name="HOA Name",
            ),
        ),
    ]
