# Generated by Django 5.0.1 on 2025-08-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0005_historicallead_hoa_name_lead_hoa_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallead",
            name="hoa_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the Homeowners Association (if applicable)",
                max_length=200,
                null=True,
                verbose_name="HOA Name",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="hoa_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the Homeowners Association (if applicable)",
                max_length=200,
                null=True,
                verbose_name="HOA Name",
            ),
        ),
    ]
