# Generated by Django 5.0.1 on 2025-08-19 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0006_alter_historicallead_hoa_name_alter_lead_hoa_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this lead",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
    ]
