# Generated by Django 5.1.4 on 2025-07-17 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="perfilfornecedor",
            old_name="usuario",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="perfilinterno",
            old_name="usuario",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="perfilsubcontratado",
            old_name="usuario",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="perfilfornecedor",
            name="cnpj",
        ),
    ]
