# Generated by Django 5.1.4 on 2025-07-18 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_rename_usuario_perfilfornecedor_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perfilsubcontratado",
            name="cnpj",
        ),
    ]
